import { Component } from '@angular/core';

function log(target: any,name: any,descriptor: any){
  //console.log(target,name,descriptor);
  const original=descriptor.value
  descriptor.value=function(...args: any){
    console.log('Arguments ',args,' were passed in this function');
    const result=original.apply(this,args)
    console.log('The result of the function is',result);
    return result
  }
  return descriptor
}
// function log(className: any){
//   console.log(className);
//   return (...args: any)=>{
//       console.log('Arguments passed to this class constructor are:',args)
//       return new className(...args)
//   }
// }
// @log
// class myExampleClass{
//   constructor(arg1: any,arg2: any){
//     console.log('Constructor fired'); 
//   }
// }
// const myClass=new myExampleClass(5,10)


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  title = 'intro2angular';
  constructor(){
    console.log("This statement was generated by the constructor ",this.aSimpleMethod(5,2))
  }
  @log
  aSimpleMethod(a: number,b:number){
    //console.log("Hey there!!");
    return a*b
    
  }
}
